services:
  api:
    build:
      context: "./.net_backend"
      dockerfile: WebAPI/Dockerfile
    ports:
      - "8080:8080"
    networks:
      - app-network

  frontend:
    build:
      context: "./vue_frontend"
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge