services:
  api:
    build:
      context: "./.net_backend"
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - app-network

  frontend_user:
    build:
      context: "./vue_frontend"
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    networks:
      - app-network

  frontend_admin:
    build:
      context: "./vue_admin_frontend"
      dockerfile: Dockerfile
    ports:
      - "8082:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge