name: Docker

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["CI/CD for .NET"]
    types: [completed]


jobs:
  publish:
    runs-on: ubuntu-latest
    if: >
      github.event_name == 'workflow_dispatch' ||
      (github.event.workflow_run.conclusion == 'success' &&
      (github.event.workflow_run.event == 'push' ||
      (github.event.workflow_run.event == 'pull_request' &&
       github.event.workflow_run.pull_request.merged == true)))
    
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push api
        uses: docker/build-push-action@v5
        with:
          context: ./.net_backend
          file: ./.net_backend/Dockerfile
          push: true
          tags: maxvaskovich/bookbuddy_api:latest

      - name: Build and push user_frontend
        uses: docker/build-push-action@v5
        with:
          context: ./vue_frontend
          file: ./vue_frontend/Dockerfile
          push: true
          tags: maxvaskovich/bookbuddy_user_frontend:latest

      - name: Build and push admin_frontend
      uses: docker/build-push-action@v5
      with:
        context: ./vue_frontend
        file: ./vue_admin_frontend/Dockerfile
        push: true
        tags: maxvaskovich/bookbuddy_admin_frontend:latest
