name: CI/CD for .NET
 
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
 
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
<<<<<<< HEAD
      run: dotnet restore ./bookbuddy_api/bookbuddy_api.sln

    - name: Build
      run: dotnet build ./bookbuddy_api/bookbuddy_api.sln --configuration Release --no-restore

    - name: Run tests
      run: dotnet test ./bookbuddy_api/bookbuddy_api.sln --no-restore --verbosity normal
=======
      run: dotnet restore ./bookbuddy_api.sln

    - name: Build
      run: dotnet build ./bookbuddy_api.sln --configuration Release --no-restore

    - name: Run tests
      run: dotnet test ./bookbuddy_api.sln --no-restore --verbosity normal
>>>>>>> origin/main
