name: CI/CD for .NET and Cypress Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore ./.net_backend/bookbuddy_api.sln

    - name: Build
      run: dotnet build ./.net_backend/bookbuddy_api.sln --configuration Release --no-restore

    - name: Run backend tests
      env:
        ASPNETCORE_ENVIRONMENT: Testing
      run: dotnet test ./.net_backend/Unit_Tests/Unit_Tests.csproj --verbosity normal
