name: CI/CD for .NET and Cypress Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore ./.net_backend/bookbuddy_api.sln

    - name: Build
      run: dotnet build ./.net_backend/bookbuddy_api.sln --configuration Release --no-restore

    - name: Run backend tests
      env:
        ASPNETCORE_ENVIRONMENT: Testing
      run: dotnet test --no-build --verbosity normal

    - name: Start the backend application
      run: dotnet run --project ./.net_backend/bookbuddy_api/bookbuddy_api.csproj --urls http://localhost:4000 &

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install frontend dependencies
      run: npm install
      working-directory: ./bookbuddy_frontend

    - name: Start the frontend application
      run: npm run dev &
      working-directory: ./bookbuddy_frontend
      env:
        CI: true

    - name: Wait for frontend and backend to be ready
      run: npx wait-on http://localhost:5173 http://localhost:4000/health
      working-directory: ./bookbuddy_frontend

    - name: Run Cypress tests
      run: npx cypress run
      working-directory: ./bookbuddy_frontend