name: CI/CD for .NET and Cypress Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore ./.net_backend/bookbuddy_api.sln

    - name: Build
      run: dotnet build ./.net_backend/bookbuddy_api.sln --configuration Release --no-restore

    - name: Run backend tests
      env:
        ASPNETCORE_ENVIRONMENT: Testing
      run: dotnet test ./.net_backend/Unit_Tests/Unit_Tests.csproj --verbosity normal

    - name: Install wait-on
      run: npm install -g wait-on

    - name: Start the backend application
      run: dotnet run --project ./.net_backend/WebAPI/WebAPI.csproj --urls "https://localhost:7023" &

    - name: Wait for backend to be ready
      run: npx wait-on https://localhost:7023/health

    - name: Log backend status
      run: curl -vk https://localhost:7023/health || true

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install frontend dependencies
      run: npm install
      working-directory: ./vue_frontend

    - name: Start the frontend application
      run: npm run dev &
      working-directory: ./vue_frontend
      env:
        CI: true

    - name: Log frontend status
      run: curl -vk http://localhost:5173 || true

    - name: Install wait-on
      run: npm install -g wait-on

    - name: Wait for frontend and backend to be ready
      run: npx wait-on http://localhost:5173 https://localhost:7023
      working-directory: ./vue_frontend

    - name: Run Cypress tests
      run: npx cypress run
      working-directory: ./vue_frontend