name: SonarQube analysis

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  pull-requests: read # allows SonarQube to decorate PRs with analysis results

jobs:
  Analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Verify Java version
        run: java -version

      - name: Test SonarQube server connectivity
        run: |
          curl -I ${{ secrets.SONAR_HOST_URL }}

      - name: Analyze with SonarQube
        uses: SonarSource/sonarqube-scan-action@7295e71c9583053f5bf40e9d4068a0c974603ec8
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: https://1d39-145-93-121-10.ngrok-free.app
          JAVA_HOME: /usr/lib/jvm/java-17-openjdk-amd64
        with:
          args: >
            -Dsonar.projectKey=bookbuddy
            -Dsonar.java.jdkHome=/usr/lib/jvm/java-17-openjdk-amd64
