name: SonarQube analysis

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  pull-requests: read # allows SonarQube to decorate PRs with analysis results

jobs:
  Analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Verify Java version
        run: java -version

      - name: Test SonarQube server connectivity
        run: |
          curl -I ${{ secrets.SONAR_HOST_URL }}

      - name: Analyze with SonarQube using custom Java 17 image
        run: |
          docker run --rm \
            -e SONAR_HOST_URL=https://1d39-145-93-121-10.ngrok-free.app/ \
            -e SONAR_TOKEN=${{ secrets.SONAR_TOKEN }} \
            -e GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} \
            -v "$(pwd)":/usr/src \
            -w /usr/src \
            openjdk:17-jdk-alpine \
            sonar-scanner \
            -Dsonar.projectKey=bookbuddy
